// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFVdehinEm6_m_Uw-6nSU_mFJ05l72JY',
    appId: '1:692590660024:ios:5171d42dc52081f599a74d',
    messagingSenderId: '692590660024',
    projectId: 'faassignment-d7dae',
    databaseURL: 'https://faassignment-d7dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'faassignment-d7dae.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFVdehinEm6_m_Uw-6nSU_mFJ05l72JY',
    appId: '1:692590660024:ios:5171d42dc52081f599a74d',
    messagingSenderId: '692590660024',
    projectId: 'faassignment-d7dae',
    databaseURL: 'https://faassignment-d7dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'faassignment-d7dae.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJGywMTnL5BorJ5Ajii1BGI7kw73LXROo',
    appId: '1:692590660024:web:47dfdae407bfe89399a74d',
    messagingSenderId: '692590660024',
    projectId: 'faassignment-d7dae',
    authDomain: 'faassignment-d7dae.firebaseapp.com',
    databaseURL: 'https://faassignment-d7dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'faassignment-d7dae.appspot.com',
    measurementId: 'G-3QSNR09VVS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGywMTnL5BorJ5Ajii1BGI7kw73LXROo',
    appId: '1:692590660024:web:47dfdae407bfe89399a74d',
    messagingSenderId: '692590660024',
    projectId: 'faassignment-d7dae',
    authDomain: 'faassignment-d7dae.firebaseapp.com',
    databaseURL: 'https://faassignment-d7dae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'faassignment-d7dae.appspot.com',
    measurementId: 'G-3QSNR09VVS',
  );

}